### ISSUE TITLE
How to use FileDirectory function

### ISSUE THREAD

**Issue by ahsanww** [robidev/iec61850_open_gateway#1] opened 2022-02-08 08:25 UTC
Hi robidev

i would like to use your iec61850 python library to download file from iec61850 server because your lib have download handler. But i cannot listing file from server. I Try like that : 
```
rootDirectory = lib61850.IedConnection_getFileDirectory(
        con, error, "/")
directoryEntry = lib61850.LinkedList_getNext(rootDirectory)
while directoryEntry:
        entry = lib61850.FileDirectoryEntry(directoryEntry)
        # entry = lib61850.toFileDirectoryEntry(directoryEntry.data)
        file_name = lib61850.FileDirectoryEntry_getFileName(entry)
        file_size = lib61850.FileDirectoryEntry_getFileSize(entry)
        print(file_name)
        print(file_size)
        directoryEntry = lib61850.LinkedList_getNext(directoryEntry)
    lib61850.LinkedList_destroy(directoryEntry)
```

And i get hex byte from filename and 0 from file size. how i can implement this? Any help is much appreciated.

**Comment by robidev** [comment] 2022-02-08 09:56
Hello,

This is not really an issue with iec61850_open_gateway, so I will close this. Please do not use the issue function for a question.

The issue is due to a wrong ctypes conversion you are making. ctypes is tricky like that.

`entry = lib61850.FileDirectoryEntry(directoryEntry)` is wrong, as it uses the linked-list pointer _address_(i.e. &directoryEntry in c), and converts it into a FileDirectoryEntry pointer. Instead you have to cast the directoryEntry->data into a FileDirectoryEntry*, like so;

`entry = ctypes.cast(lib61850.LinkedList_getData(directoryEntry),lib61850.FileDirectoryEntry)`

full working code:
```
import ctypes
import lib61850

host = "127.0.0.1"
port = 102
filename = ""

con = lib61850.IedConnection_create()
error = lib61850.IedClientError()
lib61850.IedConnection_connect(con,ctypes.byref(error), host, port)
if error.value == lib61850.IED_ERROR_OK:
    error_file = lib61850.IedClientError()
    rootDirectory = lib61850.IedConnection_getFileDirectory(con, error_file, filename)
    if error_file.value != lib61850.IED_ERROR_OK:
        print("Error retrieving file directory")
        exit(1)

    directoryEntry = lib61850.LinkedList_getNext(rootDirectory)
    while directoryEntry:
            entry = ctypes.cast(lib61850.LinkedList_getData(directoryEntry),lib61850.FileDirectoryEntry)

            file_name = lib61850.FileDirectoryEntry_getFileName(entry).decode("UTF-8")
            file_size = lib61850.FileDirectoryEntry_getFileSize(entry)

            print(file_name)
            print(file_size)

            directoryEntry = lib61850.LinkedList_getNext(directoryEntry)
    lib61850.LinkedList_destroy(directoryEntry)
else:
    print("connection issue")
```

**Closed as completed by robidev** 2022-02-08 09:56 UTC

**Comment by ahsanww** [comment] 2022-02-09 07:45
Sorry for ask a question from issue, but Thanks for your help. 
Can i ask again based on IedClientGetFileHandler, i cant implement this and returning to wrong CFunctionType. Any clue to make fileHandler function in python. Thanks

**Comment by robidev** [comment] 2022-02-10 11:13
The short answer is; `handler = lib61850.IedClientGetFileHandler(downloadHandler)` creates a callback-handler that can be passed to lib61850.IedConnection_getFile, which I assume is what you are trying to do. However, you will run into more issues regarding the parameters passed, as you are calling c-functions from python and receiving c callbacks. There is a lot of tricky stuff to get right, and I'm not going to do it all for you. Below is again a working example, but this will be my last reply;

```
import ctypes
import lib61850

def downloadHandler(parameter, buffer, bytesRead):
    filename = ctypes.cast(parameter,ctypes.c_char_p).value.decode("utf-8") # convert parameter back to python string
    print("received %i bytes for file: %s" % (bytesRead, filename))
    if bytesRead > 0:
        with open(filename, "ab") as fp:
            bytesbuffer = ctypes.string_at(buffer, bytesRead) # convert char* buffer to python buffer
            fp.write(bytesbuffer) # append bytes to file
    return True


host = "127.0.0.1"
port = 102
filename = ""

con = lib61850.IedConnection_create()
error = lib61850.IedClientError()
lib61850.IedConnection_connect(con,ctypes.byref(error), host, port)
if error.value == lib61850.IED_ERROR_OK:
    error_file = lib61850.IedClientError()
    rootDirectory = lib61850.IedConnection_getFileDirectory(con, error_file, filename)
    if error_file.value != lib61850.IED_ERROR_OK:
        print("Error retrieving file directory")
        exit(1)

    handler = lib61850.IedClientGetFileHandler(downloadHandler) # create callback handler. WARNING: 'handler' should be kept in scope during callbacks!
    directoryEntry = lib61850.LinkedList_getNext(rootDirectory)
    while directoryEntry:
            entry = ctypes.cast(lib61850.LinkedList_getData(directoryEntry),lib61850.FileDirectoryEntry)

            file_name = lib61850.FileDirectoryEntry_getFileName(entry).decode("UTF-8")
            file_size = lib61850.FileDirectoryEntry_getFileSize(entry)

            print(file_name)
            print(file_size)

            open(file_name, "w").close() # create an empty file
            error_getfile = lib61850.IedClientError()
            file_name_array = bytes(file_name.encode('utf-8')) # convert python string to bytearray 
            lib61850.IedConnection_getFile(con, error_getfile, file_name, handler, ctypes.c_char_p( file_name_array ))
            if error_getfile.value != lib61850.IED_ERROR_OK:
                print("Failed to get file!")


            directoryEntry = lib61850.LinkedList_getNext(directoryEntry)
    lib61850.LinkedList_destroy(directoryEntry)
else:
    print("connection issue") 
```

**Comment by ahsanww** [comment] 2022-02-14 04:45
Ok Thank for your help
